version: "2"
services:
  web:
    image: jacksonveroneze/php7.1-fpm-nginx
    ports:
      - "4443:443"
    volumes:
      - /home/jackson/www/e-school:/home/www/workdir
      - $DIR_SSH:/home/www/.ssh
      - $DIR_COMPOSER:/home/www/.composer
      - $DIR_TMP_E_SCHOOL:/home/www/.tmp
    working_dir: /home/www/workdir
    links:
    - db
    - cache
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - $DIR_DATA_STORAGE_E_SCHOOL:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD_STORAGE
  cache:
    image: memcached
    ports:
      - "11211:11211"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: $PASSWORD_STORAGE
    links:
    - db