version: "2"
services:
  web:
    image: jacksonveroneze/php7.0-fpm-nginx
    ports:
      - "4445:443"
    volumes:
      - /home/jackson/www/e-school:/home/www/workdir
      - /home/jackson/.ssh/:/home/www/.ssh
      - /home/jackson/.composer/:/home/www/.composer
    working_dir: /home/www/workdir
    links:
    - db
    - cache
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /home/jackson/.datastorage/mysql/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: l@08ESCOL@
  cache:
    image: memcached
    ports:
      - "11215:11211"