version: "2"
services:
  web:
    image: jacksonveroneze/php7.0-fpm-nginx
    ports:
      - "4443:443"
    volumes:
      - /home/jackson/www/g-mas-dev:/home/www/workdir
      - $DIR_SSH:/home/www/.ssh
      - $DIR_COMPOSER:/home/www/.composer
      - $DIR_TMP:/home/www/.tmp
    working_dir: /home/www/workdir
    links:
    - db
    - cache
    - mordomo
  db:
    image: jacksonveroneze/postgres9.4-ssl
    ports:
      - "5432:5432"
    volumes:
      - $DIR_DATA_STORAGE_GMAS:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: $PASSWORD_STORAGE
  cache:
    image: memcached
    ports:
      - "11211:11211"
  mordomo:
    image: openjdk:7-jre
    ports:
    - "7001:7001"
    volumes: 
        - /home/jackson/www/g-mas-dev:/home/www/workdir:rw
        - $DIR_TMP:/home/www/.tmp:rw
    working_dir: /home/www/workdir/library/vendor/inovadora/mordomo
    command: java -jar Mordomo.jar
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - $DIR_PGADMIN_DATA:/data/
    links:
    - db