version: "2"
services:
  web:
    image: jacksonveroneze/nginx-php
    ports:
      - "4443:443"
    volumes:
      - /home/$USER/www/g-mus-dev:/home/developer/workdir
      - $DIR_TMP:/home/developer/.tmp
    links:
    - fpm
  fpm:
    image: jacksonveroneze/php7.0-fpm
    volumes:
      - /home/$USER/www/g-mus-dev:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
    - db
    - cache
  db:
    image: jacksonveroneze/postgres9.4-ssl
    ports:
      - "5432:5432"
    volumes:
      - $DIR_DATA_STORAGE_GMUS:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: $PASSWORD_STORAGE
  cache:
    image: memcached
    ports:
      - "11213:11211"
  mordomo:
    image: openjdk:7-jre
    ports:
    - "7001:7001"
    volumes: 
        - /home/$USER/www/g-mus-dev:/home/developer/workdir:rw
        - $DIR_TMP:/home/developer/.tmp:rw
    working_dir: /home/developer/workdir/library/vendor/inovadora/mordomo
    command: java -jar Mordomo.jar
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - $DIR_PGADMIN_DATA:/data/
    links:
    - db