version: "3"
services:

  ###########################################################################

  web1:
    image: jacksonveroneze/nginx-php
    ports:
      - 4445:443
    volumes:
      - /home/$USER/www/e-school:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
      - db
      - memcached
      - memcached_session

  ###########################################################################

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - $DIR_DATA_STORAGE_E_SCHOOL:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD_STORAGE

  ###########################################################################

  memcached:
    image: memcached
    command: -m 512 -t 4

  memcached_session:
    image: memcached
    command: -I 5M -m 64 -t 4

  ###########################################################################

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: $PASSWORD_STORAGE
    links:
      - db