version: "3"
services:

  ###########################################################################
  # BALANCE
  ###########################################################################

  balance:
    image: jacksonveroneze/nginx-balance
    ports:
      - 4443:443
    links:
      - web1
      - web2


  ###########################################################################
  # WEBs
  ###########################################################################

  web1:
    image: jacksonveroneze/nginx-php
    volumes:
      - /home/$USER/www/g-mus-dev:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
      - db
      - memcached
      - memcached_session
      - redis

  web2:
    image: jacksonveroneze/nginx-php
    volumes:
      - /home/$USER/www/g-mus-dev:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
      - db
      - memcached
      - memcached_session
      - redis

  ###########################################################################
  # POSTGRES
  ###########################################################################

  db:
    image: jacksonveroneze/postgres9.4-ssl
    ports:
      - "5432:5432"
    volumes:
      - $DIR_DATA_STORAGE_GMUS:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $PASSWORD_STORAGE
  
  ###########################################################################
  # CACHES
  ###########################################################################

  memcached:
    image: memcached
    command: -m 512 -t 4

  memcached_session:
    image: memcached
    command: -I 5M -m 64 -t 4

  redis:
    image: redis

  ###########################################################################
  # MORDOMO
  ###########################################################################

  mordomo:
    image: openjdk:7-jre
    volumes: 
      - /home/$USER/www/g-mus-dev:/home/developer/workdir:rw
      - $DIR_TMP:/home/developer/.tmp:rw
    working_dir: /home/developer/workdir/library/vendor/inovadora/mordomo
    command: java -jar Mordomo.jar
    links:
      - db
    depends_on:
      - db

  ###########################################################################
  # ADMINs
  ###########################################################################
  
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
    volumes:
      - $DIR_PGADMIN_DATA:/data/
    links:
      - db

  redis_admin:
    image: faktiva/php-redis-admin
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 4935:80
    links:
      - redis

  ###########################################################################
  # ELASTICSEARCH
  ###########################################################################

  auth_elasticsearch:
    image: jacksonveroneze/nginx-proxy-basic-auth
    ports:
      - 4445:443
    environment:
      - FORWARD_HOST=elasticsearch
      - FORWARD_PORT=9200
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - $DIR_DATA_STORAGE_ELASTICSEARCH_GMUS:/usr/share/elasticsearch/data
      - /home/$USER/www/docker/shared/elk/product.elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml