version: "2"
services:
  web:
    image: jacksonveroneze/php7.0-fpm-nginx
    ports:
      - "4444:443"
    volumes:
      - /home/jackson/www/g-mas-dev:/home/www/workdir
      - /home/jackson/.ssh/:/home/www/.ssh
      - /home/jackson/.composer/:/home/www/.composer
      - /tmp/gemas/:/tmp
    links:
    - db
    - cache
  db:
    image: jacksonveroneze/postgres9.4-ssl
    ports:
      - "5433:5432"
    volumes:
      - /home/jackson/.datastorage/postgres/gemas/:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: inoino
  cache:
    image: memcached
    ports:
      - "11212:11211"