version: "2"
services:
  web:
    image: jacksonveroneze/php7.0-fpm-nginx
    ports:
      - "4443:443"
    volumes:
      - /home/jackson/www/g-mus:/home/www/workdir
      - $DIR_SSH:/home/www/.ssh
      - $DIR_COMPOSER:/home/www/.composer
      - $DIR_TMP:/home/www/.tmp
    working_dir: /home/www/workdir
    links:
    - db
    - cache
  db:
    image: jacksonveroneze/postgres9.4-ssl
    ports:
      - "5432:5432"
    volumes:
      - /home/jackson/.datastorage/postgres/gmus/:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: 0ac03851e944231e8b05e553dc6637f8
  cache:
    image: memcached
    ports:
      - "11211:11211"
  mordomo:
    image: openjdk:7-jre
    ports:
    - "7001:7001"
    volumes: 
        - /home/jackson/www/g-mus-dev:/home/www/workdir:rw
        - /home/jackson/.tmp/:/home/www/.tmp:rw
    working_dir: /home/www/workdir/library/vendor/inovadora/mordomo
    command: java -jar Mordomo.jar
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - /home/jackson/.tmp/pgadmin:/data/
    links:
    - db