version: "3"
services:

  ###########################################################################

  balance:
    image: jacksonveroneze/nginx-balance
    ports:
      - 4443:443
    links:
      - web1
      - web2

  ###########################################################################

  web1:
    image: jacksonveroneze/nginx-php
    volumes:
      - /home/$USER/www/g-mas:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
      - db
      - memcached
      - memcached_session
      - redis

  web2:
    image: jacksonveroneze/nginx-php
    volumes:
      - /home/$USER/www/g-mas:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
      - db
      - memcached
      - memcached_session
      - redis

  ###########################################################################

  db:
    image: jacksonveroneze/postgres9.4-ssl
    ports:
      - "5432:5432"
    volumes:
      - $DIR_DATA_STORAGE_GMAS:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $PASSWORD_STORAGE
  
  ###########################################################################

  memcached:
    image: memcached
    command: -m 512 -t 4

  memcached_session:
    image: memcached
    command: -I 5M -m 64 -t 4

  redis:
    image: redis

  ###########################################################################

  mordomo:
    image: openjdk:7-jre
    volumes: 
      - /home/$USER/www/g-mas:/home/developer/workdir:rw
      - $DIR_TMP:/home/developer/.tmp:rw
    working_dir: /home/developer/workdir/library/vendor/inovadora/mordomo
    command: java -jar Mordomo.jar

  ###########################################################################
  
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
    volumes:
      - $DIR_PGADMIN_DATA:/data/
    links:
      - db

  redis_admin:
    image: faktiva/php-redis-admin
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 4935:80
    links:
      - redis