version: "2"
services:
  web:
    image: jacksonveroneze/nginx-php
    ports:
      - "4443:443"
    volumes:
      - /home/$USER/www/e-school:/home/developer/workdir
      - $DIR_TMP:/home/developer/.tmp
    links:
    - fpm
  fpm:
    image: jacksonveroneze/php7.1-fpm
    volumes:
      - /home/$USER/www/e-school:/home/developer/workdir
      - $DIR_SSH:/home/developer/.ssh
      - $DIR_COMPOSER:/home/developer/.composer
      - $DIR_TMP:/home/developer/.tmp
    links:
    - db
    - cache
    - cache_session
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - $DIR_DATA_STORAGE_E_SCHOOL:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $PASSWORD_STORAGE
  cache:
    image: memcached
    ports:
      - "11211:11211"
  cache_session:
    image: memcached
    ports:
      - "11215:11211"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: $PASSWORD_STORAGE
    links:
    - db