sudo: required

language: bash

services:
  - docker

script:
  - cd php7.0-fpm-nginx
  - ./docker-build.sh
  - cd ../postgres9.4-ssl
  - ./docker-build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jacksonveroneze/php7.0-fpm-nginx;
    docker push jacksonveroneze/postgres9.4-ssl;
    fi

notifications:
  email:
    - jackson@jacksonveroneze.com