sudo: required

language: bash

services:
  - docker

script:
  - cd scripts
  - ./docker-build-debian.sh
  - ./docker-build-nginx.sh
  - ./docker-build-php.sh
  - ./docker-build-postgres

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jacksonveroneze/php7.0-fpm-nginx;
    docker push jacksonveroneze/php7.1-fpm-nginx;
    docker push jacksonveroneze/postgres9.4-ssl;
    fi

notifications:
  email:
    - jackson@jacksonveroneze.com