sudo: required

language: bash

services:
  - docker

script:
  - cd scripts
  - ./docker-build-debian.sh
  - ./docker-build-nginx.sh
  - ./docker-build-php-nginx.sh
  - ./docker-build-postgres.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then

    fi

notifications:
  email:
    - jackson@jacksonveroneze.com